apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp-{{ .Values.activeService}}-deployment
  labels: 
    app: vproapp-{{ .Values.activeService}}
    version: {{ .Values.activeService}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp-{{ .Values.activeService}}
      version: {{ .Values.activeService}}
  template:
    metadata:
      labels:
        app: vproapp-{{ .Values.activeService}}
        version: {{ .Values.activeService}}
    spec:
      containers:
      - name: deploy-vproapp-{{ .Values.activeService}}
        image: {{ .Values.appimage}}:{{ .Values.apptag}}
        ports:
        - name: vproapp-port
          containerPort: 80
      initContainers:
      - name: init-mydb
        image: busybox
        command: ['sh', '-c', 'until nslookup vprodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
      - name: init-memcache
        image: busybox
        command: ['sh', '-c', 'until nslookup vprocache01.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
