apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
  labels:
    app: vproapp-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: vproapp-{{ .Values.activeService}}
    version: {{ .Values.activeService}}
  
