apiVersion: v1
kind: Service
metadata:
  name: vproapp-blue
  labels:
    app: vproapp-blue
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: vproapp-blue
  type: ClusterIP
