name: PR Merge
# on: workflow_dispatch
on:
  push:
    branches:
      - main
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: vprofileapp
  EKS_CLUSTER: vprofileapp-eks

jobs:
  Build_Package:
    name: Package application
    runs-on: ubuntu-latest
    steps:   
      - name: Code checkout
        uses: actions/checkout@v4 
   
      - name: Package application
        run: mvn package    