name: PR Merge
## on: workflow_dispatch
on:
  push:
    branches:
      - main
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: vprofileapp
  EKS_CLUSTER: vprofileapp-eks

jobs:
  Build_Docker_Image:
    name: Build docker image 
    runs-on: ubuntu-latest
    
    steps:   
      - name: Code checkout
        uses: actions/checkout@v4 
   
      - name: Build docker image & upload to ECR
        uses: appleboy/docker-ecr-action@master
        with: 
          access_key: ${{ secrets.AWS_ACCESS_KEY }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          registry: ${{ secrets.REGISTRY }}
          repo: ${{ env.ECR_REPOSITORY }}
          region: ${{ env.REGION }}
          tags: latest, ${{ github.run_number }}
          daemon_off: false
          dockerfile: ./Dockerfile
          context: ./ 